### ISSUE TITLE
Create new entries!

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/TLDR.jl#2]
This is an endless job, but hopefully, you can help.

Here's a simple guide, but feel free to contact us.

---
# Hacktoberfest

- If there are many small Pull Requests, DigitalOcean may flag the repo as invalid.
- So please submit a new entry with a few snippets per Pull Request.
- **Submitting only a new package header will be marked as invalid**.
- I will give preference to the first PR with at least 3 snippets for a given package.
- But if you leave a comment below saying that you're working on a PR, I will give preference to your package within 1 hour of your comment - unless you don't make 3 snippets.
---

## Formatting guidelines

_These are modified as the package increases._

- Description (except in headers): Use the imperative: "Get", "Do", "Solve", "Find";
- Tags: Use lowercase and separate words by `-`: `julia-snippets`, `linear-algebra`;
- Multiline snippets: Use `\n  ` to separate lines, i.e., add the line break `\n` between each line, and use two-space indentation. See `cmd:cholesky` for an example.

## Simple contributing guide:

We have created a couple of commands:

### `new_pkg(pkg, description, tags)`

Create a new entry for `pkg` using the `description` and some `tags`.

### `new_snippet([pkg=""], cmd, description, tags)`

Create a new entry (that can be associated to a `pkg`) for a snippet `cmd`.

### Short guide

- Fork this repo
- Clone your repo, create a branch for your contribution(s)
- Go inside, run `julia --project`
- Instantiate the project: `]` becomes `pkg>`, then `pkg> instantiate`
- `using Jet`
- Use `new_pkg` or `new_snippet`
- Commit with a message like "New package: ..." or "New snippet for how to ..."
- Push to your repo, and create a PR to our `main` branch

You can watch a asciinema recording below (But I forgot to commit):

[![asciicast](https://asciinema.org/a/362685.svg)](https://asciinema.org/a/362685)

Note: We use `rebase` and `squash` merges, so `fetch` this repo from time to time and update your `main` branch related to this one. Always branch from `main`.

**Comment by Nibba2018** [comment]
Hello @abelsiqueira , I would like to contribute to this issue. What other packages would you like me to cover?

Also, kindly add `hacktoberfest` topic to this repo according to the new rules to qualify PRs. You read more about the rules [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by abelsiqueira** [comment]
Hi @Nibba2018, I don't have any current restrictions on which packages to add. I good list could probably be the ones from "Popular packages" [here](https://juliahub.com/ui/Home).

**Comment by abelsiqueira** [comment]
And I added the topic, thanks for the heads up.

**Comment by Nibba2018** [comment]
@abelsiqueira How do I know which packages are already implemented?

**Comment by abelsiqueira** [comment]
Not much, here's the data: https://github.com/abelsiqueira/Jet.jl/blob/main/data.json
Essentially, this package, and one line from DataFrames. Creating a better visualization of this is also an open issue, sorry.

**Comment by abelsiqueira** [comment]
The site and package have been updated and a contributing guide is online: https://abelsiqueira.github.io/TLDR.jl/contributing/
