### ISSUE TITLE
Pretty printing

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/TLDR.jl#7]
Format output to correctly print like the help.

**Comment by ParthPant** [comment]
Hey, I'm new to Julia but would love to work on this issue. Can you tell be what sort of formatting you have in mind.
The standard julia REPL most likely uses` printstyled()` to print colors to the terminal but `Crayons.jl `is another Package that can be used for this.

**Comment by abelsiqueira** [comment]
Hi @ParthPant, thanks for the interest in this. I was thinking something like the `help` but respecting the line breaks. I believe the help is parsed as Markdown, but in this case we can't just pass everything to Markdown. In essence:

- code highlighting of the snippets;
- markdown highlighting of the description;
- make sure it doesn't "eat" line breaks.

Using Crayons might be the solution, I noticed that's what OhMyRepl uses.

**Comment by abelsiqueira** [comment]
Done in #20
